version: '3.7'

services:
  minecraft:
    image: itzg/minecraft-server:latest
    environment:
      CONSOLE: "false"
      ENABLE_RCON: "true"
      EULA: "TRUE"
      LEVEL_TYPE: LARGEBIOMES
      MAX_BUILD_HEIGHT: 256
      MAX_MEMORY: 2G
      MAX_PLAYERS: 100
      RCON_PASSWORD: ${MINECRAFT_RCON_PASSWORD:-b32cec4dac8a03fcc24cc7db6bba750c}
      RCON_PORT: 25575
      VIEW_DISTANCE: 15
    ports:
    - 25565:25565/tcp
    - 25575:25575/tcp
    restart: always
    volumes:
    - ~/minecraft/config:/config:rw
    - ~/minecraft/data:/data:rw
    - ~/minecraft/mods:/mods:rw
  rcon:
    image: itzg/rcon:latest
    ports:
    - 4326:4326/tcp
    - 4327:4327/tcp
    volumes:
    - minecraft-rcon:/opt/rcon-web-admin/db:rw

volumes:
  minecraft-rcon: {}
