version: '3.7'

services:
  pihole:
    image: pihole/pihole:latest
    dns:
    - 127.0.0.1
    - 9.9.9.9
    - 9.9.9.10
    environment:
      DNS1: 9.9.9.9
      DNS2: 9.9.9.10
      TZ: UTC
      WEBPASSWORD: ${PIHOLE_WEB_PASSWORD:-76c9eca2bced3e751a47c188afe6fd9d}
    ports:
    - 53:53/tcp
    - 53:53/udp
    - 67:67/udp
    - 80:80/tcp
    - 443:443/tcp
    restart: unless-stopped
    volumes:
    - pihole-volume-pihole:/etc/pihole/:rw
    - pihole-volume-dnsmasq:/etc/dnsmasq.d/:rw

volumes:
  pihole-volume-dnsmasq: {}
  pihole-volume-pihole: {}
