version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:management
    environment:
    - RABBITMQ_DEFAULT_PASS_FILE=/run/secrets/rabbitmq-password
    - RABBITMQ_DEFAULT_USER_FILE=/run/secrets/rabbitmq-username
    ports:
    - 5672:5672/tcp
    - 15672:15672/tcp
    secrets:
    - source: rabbitmq-password
    - source: rabbitmq-username
    volumes:
    - rabbitmq-volume:/var/lib/rabbitmq:rw

secrets:
  rabbitmq-password:
    external: true
    name: rabbitmq-password
  rabbitmq-username:
    external: true
    name: rabbitmq-username

volumes:
  rabbitmq-volume: {}
