version: '3.7'

services:
  server:
    image: jetbrains/teamcity-server:latest
    ports:
    - 8111:8111/tcp
    volumes:
    - ~/teamcity/datadir:/data/teamcity_server/datadir:rw
    - ~/teamcity/logs:/opt/teamcity/logs:rw

  agent-dotnet5:
    image: eassbhhtgu/teamcity-net5-agent:latest
    depends_on:
    - server
    environment:
      AGENT_NAME: dotnet5
      DOCKER_IN_DOCKER: start
      SERVER_URL: server:8111
    ports:
    - 9090:9090/tcp
    volumes:
    - ~/teamcity/agent-conf:/data/teamcity_agent_dotnet5/conf:rw
    - agent-docker:/var/lib/docker:rw

volumes:
  agent-docker: {}
